sudo: false
matrix:
  include:
    - language: node_js
      node_js:
        - 10
    -language: python
      python:
        - 3.8
before_install:
  - python -m pip install --user vertualenv
install:
  - npm install
script:
  - npm test
